news_sites:
  eluniversal:
    url: https://www.eluniversal.com.mx
    queries:
      homepage_articule_links: '.field-content a'
      article_body: '.field-name-body'
      article_title: '.pane-content h1'
  elpais:
    url: https://elpais.com
    queries:
      homepage_articule_links: '.articulo-titulo a'
      article_body: '.articulo-cuerpo'
      article_title: '.articulo-titulo'
  eldeforma:
    url: https://eldeforma.com/
    queries:
      homepage_articule_links: '.article__header  a'
      article_body: '.article__content'
      article_title: '.article--title'
